-- Importar notícias e dados relacionados

-- NOTÍCIAS DE TESTE
INSERT INTO noticias (titulo, slug, subtitulo, conteudo, resumo, autor_id, categoria_id, status, destaque, data_publicacao, visualizacoes, curtidas, imagem_destaque, meta_title, meta_description) VALUES 

-- Política
('Nova Lei de Transparência é Aprovada no Congresso', 'nova-lei-transparencia-aprovada-congresso', 'Medida visa aumentar o acesso à informação pública', '<p>O Congresso Nacional aprovou hoje uma nova lei que amplia significativamente o acesso à informação pública no país. A medida, que tramitava há dois anos, estabelece novos prazos para resposta aos pedidos de informação e cria mecanismos mais eficazes de fiscalização.</p><p>Segundo o relator do projeto, a nova legislação representa um marco na transparência pública brasileira. "Estamos dando um passo importante para fortalecer a democracia e o controle social", declarou.</p><p>A lei entra em vigor em 90 dias e afeta todos os órgãos públicos federais, estaduais e municipais.</p>', 'Congresso aprova nova lei que amplia acesso à informação pública com prazos menores e fiscalização mais eficaz.', 1, 1, 'publicado', 1, '2024-01-15 10:30:00', 1250, 89, '/uploads/noticias/congresso-lei.jpg', 'Nova Lei de Transparência Aprovada - Portal Notícias', 'Congresso aprova lei que amplia acesso à informação pública com novos prazos e mecanismos de fiscalização'),

('Prefeito de São Paulo Anuncia Novo Plano de Mobilidade', 'prefeito-sp-anuncia-plano-mobilidade', 'Investimento de R$ 2 bilhões em transporte público', '<p>O prefeito de São Paulo anunciou hoje um ambicioso plano de mobilidade urbana que prevê investimentos de R$ 2 bilhões nos próximos quatro anos. O projeto inclui a expansão do metrô, criação de novas ciclovias e modernização da frota de ônibus.</p><p>"Nossa meta é reduzir em 30% o tempo de deslocamento na cidade até 2028", afirmou o prefeito durante coletiva de imprensa. O plano também prevê a integração total entre os diferentes modais de transporte.</p><p>As obras devem começar no segundo semestre deste ano, priorizando as regiões periféricas da cidade.</p>', 'Prefeito anuncia plano de R$ 2 bilhões para melhorar mobilidade urbana em São Paulo com expansão do metrô e ciclovias.', 1, 1, 'publicado', 1, '2024-01-15 14:15:00', 980, 67, '/uploads/noticias/mobilidade-sp.jpg', 'Plano de Mobilidade São Paulo - R$ 2 Bilhões', 'Prefeito anuncia investimento de R$ 2 bilhões em mobilidade urbana com expansão do metrô e ciclovias'),

-- Economia
('Inflação Fecha 2023 em 4,62%, Dentro da Meta', 'inflacao-fecha-2023-meta', 'IPCA fica abaixo do teto estabelecido pelo governo', '<p>A inflação oficial do país, medida pelo Índice Nacional de Preços ao Consumidor Amplo (IPCA), fechou 2023 em 4,62%, ficando dentro da meta estabelecida pelo Conselho Monetário Nacional, que era de 3,25% com tolerância de 1,5 ponto percentual para mais ou para menos.</p><p>O resultado representa uma desaceleração em relação ao ano anterior e reflete a eficácia das políticas monetárias adotadas pelo Banco Central. Os grupos que mais contribuíram para a inflação foram habitação e alimentação.</p><p>Economistas avaliam que o cenário é positivo para 2024, com expectativas de inflação ainda mais controlada.</p>', 'IPCA fecha 2023 em 4,62%, dentro da meta governamental, sinalizando controle da inflação e perspectivas positivas.', 1, 2, 'publicado', 1, '2024-01-15 08:45:00', 1450, 102, '/uploads/noticias/inflacao-2023.jpg', 'Inflação 2023: 4,62% Dentro da Meta', 'IPCA fecha 2023 em 4,62%, dentro da meta do governo, com perspectivas positivas para 2024'),

('Dólar Fecha em Queda Após Decisão do Fed', 'dolar-queda-decisao-fed', 'Moeda americana recua 1,2% frente ao real', '<p>O dólar fechou em queda de 1,2% nesta quarta-feira, cotado a R$ 4,95, após a decisão do Federal Reserve (Fed) de manter as taxas de juros inalteradas nos Estados Unidos. A decisão era esperada pelo mercado, mas os comentários do presidente do Fed sobre possíveis cortes futuros animaram os investidores.</p><p>No mercado doméstico, a melhora do cenário fiscal brasileiro também contribuiu para o fortalecimento do real. Analistas projetam que a moeda pode se manter estável nas próximas semanas.</p><p>O Ibovespa acompanhou o movimento positivo, fechando em alta de 0,8%.</p>', 'Dólar recua 1,2% após decisão do Fed de manter juros, com real se fortalecendo no cenário doméstico.', 1, 2, 'publicado', 0, '2024-01-15 16:20:00', 890, 45, '/uploads/noticias/dolar-queda.jpg', 'Dólar em Queda Após Decisão do Fed', 'Dólar recua 1,2% frente ao real após Fed manter juros, com perspectivas positivas para o mercado'),

-- Esportes
('Brasil Vence Argentina por 2x1 em Amistoso Emocionante', 'brasil-vence-argentina-amistoso', 'Seleção brasileira mostra evolução sob novo técnico', '<p>A Seleção Brasileira venceu a Argentina por 2 a 1 em amistoso disputado no Maracanã, diante de mais de 70 mil torcedores. Os gols brasileiros foram marcados por Vinícius Jr. e Rodrygo, enquanto Messi descontou para os argentinos.</p><p>O técnico da Seleção elogiou a performance da equipe: "Vejo uma evolução clara no nosso padrão de jogo. Os jogadores estão entendendo melhor a proposta tática". O resultado marca a terceira vitória consecutiva do Brasil sob o novo comando técnico.</p><p>A próxima partida da Seleção será contra o Uruguai, em Montevidéu, pelas Eliminatórias da Copa do Mundo.</p>', 'Brasil vence Argentina por 2x1 no Maracanã com gols de Vinícius Jr. e Rodrygo, mostrando evolução tática.', 2, 3, 'publicado', 1, '2024-01-14 22:30:00', 2100, 156, '/uploads/noticias/brasil-argentina.jpg', 'Brasil 2x1 Argentina - Amistoso no Maracanã', 'Brasil vence Argentina por 2x1 no Maracanã com gols de Vinícius Jr. e Rodrygo em grande partida'),

-- Tecnologia
('Nova IA da Google Supera GPT-4 em Testes de Raciocínio', 'nova-ia-google-supera-gpt4', 'Gemini Ultra mostra avanços significativos em múltiplas áreas', '<p>O Google anunciou hoje que sua nova inteligência artificial, Gemini Ultra, superou o GPT-4 da OpenAI em diversos benchmarks de raciocínio e compreensão. Os testes incluíram matemática, programação, análise de texto e raciocínio lógico.</p><p>"Este é um marco importante para a IA", declarou o CEO do Google. "O Gemini Ultra representa um salto qualitativo na capacidade de processamento e compreensão de contexto". A nova IA será integrada aos produtos Google nos próximos meses.</p><p>Especialistas em IA consideram que essa evolução pode acelerar ainda mais o desenvolvimento de aplicações práticas da inteligência artificial.</p>', 'Google lança Gemini Ultra, IA que supera GPT-4 em testes de raciocínio e será integrada aos produtos da empresa.', 3, 4, 'publicado', 1, '2024-01-15 13:45:00', 1890, 201, '/uploads/noticias/gemini-ultra.jpg', 'Gemini Ultra Supera GPT-4 em Testes', 'Nova IA do Google supera GPT-4 em benchmarks de raciocínio e será integrada aos produtos da empresa'),

-- Saúde
('Novo Tratamento Reduz Câncer de Mama em 70%', 'novo-tratamento-cancer-mama-70', 'Terapia inovadora mostra resultados promissores', '<p>Pesquisadores brasileiros desenvolveram um novo tratamento para câncer de mama que reduziu tumores em 70% dos casos testados. A terapia combina imunoterapia com nanotecnologia, permitindo ataques mais precisos às células cancerígenas.</p><p>"Os resultados são extremamente promissores", afirmou a coordenadora da pesquisa. "Estamos vendo uma resposta muito melhor do que os tratamentos convencionais, com menos efeitos colaterais".</p><p>O estudo, realizado em parceria com universidades americanas, deve entrar na fase 3 de testes clínicos ainda este ano. Se aprovado, o tratamento pode estar disponível em 2026.</p>', 'Pesquisadores brasileiros desenvolvem tratamento que reduz câncer de mama em 70% com menos efeitos colaterais.', 4, 5, 'publicado', 1, '2024-01-15 09:15:00', 2200, 245, '/uploads/noticias/cancer-mama-tratamento.jpg', 'Novo Tratamento Reduz Câncer de Mama em 70%', 'Pesquisadores brasileiros desenvolvem terapia inovadora que reduz câncer de mama em 70% dos casos');